
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.8.0
 * Query Engine version: 3c6e192761c0362d496ed980de936e2f3cebcd3a
 */
Prisma.prismaVersion = {
  client: "7.8.0",
  engine: "3c6e192761c0362d496ed980de936e2f3cebcd3a"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.IncidentLogScalarFieldEnum = {
  id: 'id',
  shipmentId: 'shipmentId',
  raisedById: 'raisedById',
  reason: 'reason',
  resolved: 'resolved',
  createdAt: 'createdAt'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  phoneNumber: 'phoneNumber',
  passwordHash: 'passwordHash',
  firstName: 'firstName',
  lastName: 'lastName',
  role: 'role',
  status: 'status',
  avatarUrl: 'avatarUrl',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SavedAddressScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  label: 'label',
  type: 'type',
  street: 'street',
  city: 'city',
  state: 'state',
  country: 'country',
  postalCode: 'postalCode',
  latitude: 'latitude',
  longitude: 'longitude',
  isDefault: 'isDefault',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RiderProfileScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  nin: 'nin',
  driversLicense: 'driversLicense',
  isOnline: 'isOnline',
  ratingAverage: 'ratingAverage',
  currentHubId: 'currentHubId',
  activeVehicleId: 'activeVehicleId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  completedDeliveries: 'completedDeliveries',
  trustScore: 'trustScore'
};

exports.Prisma.VehicleScalarFieldEnum = {
  id: 'id',
  ownerId: 'ownerId',
  type: 'type',
  make: 'make',
  model: 'model',
  year: 'year',
  plateNumber: 'plateNumber',
  color: 'color',
  insuranceExpiry: 'insuranceExpiry',
  isVerified: 'isVerified',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BusinessProfileScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  businessName: 'businessName',
  registrationNumber: 'registrationNumber',
  logoUrl: 'logoUrl',
  website: 'website',
  marketplaceStoreId: 'marketplaceStoreId',
  isMarketplaceVendor: 'isMarketplaceVendor',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TransitHubScalarFieldEnum = {
  id: 'id',
  name: 'name',
  street: 'street',
  city: 'city',
  state: 'state',
  latitude: 'latitude',
  longitude: 'longitude',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ShipmentScalarFieldEnum = {
  id: 'id',
  trackingCode: 'trackingCode',
  status: 'status',
  tier: 'tier',
  pickupAddress: 'pickupAddress',
  pickupLat: 'pickupLat',
  pickupLng: 'pickupLng',
  recipient: 'recipient',
  recipientPhone: 'recipientPhone',
  dropoffAddress: 'dropoffAddress',
  dropoffLat: 'dropoffLat',
  dropoffLng: 'dropoffLng',
  packageType: 'packageType',
  packageWeightClass: 'packageWeightClass',
  specialNotes: 'specialNotes',
  isCashCollection: 'isCashCollection',
  codAmount: 'codAmount',
  isInsured: 'isInsured',
  insurancePremium: 'insurancePremium',
  isHouseMoving: 'isHouseMoving',
  baseFare: 'baseFare',
  distanceFare: 'distanceFare',
  surgePremium: 'surgePremium',
  totalPrice: 'totalPrice',
  riderShare: 'riderShare',
  platformShare: 'platformShare',
  customerId: 'customerId',
  businessId: 'businessId',
  riderId: 'riderId',
  currentHubId: 'currentHubId',
  marketplaceOrderId: 'marketplaceOrderId',
  promoCodeId: 'promoCodeId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  escrowReleaseAt: 'escrowReleaseAt',
  isSmartDelivery: 'isSmartDelivery',
  smartDeliveryPhotos: 'smartDeliveryPhotos',
  verificationPin: 'verificationPin'
};

exports.Prisma.RiderAssignmentScalarFieldEnum = {
  id: 'id',
  shipmentId: 'shipmentId',
  riderId: 'riderId',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TrackingLogScalarFieldEnum = {
  id: 'id',
  shipmentId: 'shipmentId',
  latitude: 'latitude',
  longitude: 'longitude',
  bearing: 'bearing',
  createdAt: 'createdAt'
};

exports.Prisma.StatusTimelineScalarFieldEnum = {
  id: 'id',
  shipmentId: 'shipmentId',
  status: 'status',
  description: 'description',
  changedBy: 'changedBy',
  createdAt: 'createdAt'
};

exports.Prisma.WalletScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  balance: 'balance',
  currency: 'currency',
  updatedAt: 'updatedAt'
};

exports.Prisma.TransactionScalarFieldEnum = {
  id: 'id',
  walletId: 'walletId',
  amount: 'amount',
  type: 'type',
  category: 'category',
  referenceCode: 'referenceCode',
  description: 'description',
  createdAt: 'createdAt'
};

exports.Prisma.PromoCodeScalarFieldEnum = {
  id: 'id',
  code: 'code',
  discount: 'discount',
  isPercentage: 'isPercentage',
  expiryDate: 'expiryDate',
  usageLimit: 'usageLimit',
  usedCount: 'usedCount',
  isActive: 'isActive'
};

exports.Prisma.ReviewScalarFieldEnum = {
  id: 'id',
  shipmentId: 'shipmentId',
  reviewerId: 'reviewerId',
  riderId: 'riderId',
  rating: 'rating',
  comment: 'comment',
  createdAt: 'createdAt'
};

exports.Prisma.NotificationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  title: 'title',
  body: 'body',
  channel: 'channel',
  isRead: 'isRead',
  createdAt: 'createdAt'
};

exports.Prisma.SupportTicketScalarFieldEnum = {
  id: 'id',
  creatorId: 'creatorId',
  subject: 'subject',
  description: 'description',
  status: 'status',
  priority: 'priority',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.UserRole = exports.$Enums.UserRole = {
  CUSTOMER: 'CUSTOMER',
  BUSINESS_OWNER: 'BUSINESS_OWNER',
  RIDER: 'RIDER',
  ADMIN: 'ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN'
};

exports.IdentityStatus = exports.$Enums.IdentityStatus = {
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
  SUSPENDED: 'SUSPENDED'
};

exports.AddressType = exports.$Enums.AddressType = {
  HOME: 'HOME',
  OFFICE: 'OFFICE',
  WAREHOUSE: 'WAREHOUSE',
  PICKUP_POINT: 'PICKUP_POINT'
};

exports.VehicleType = exports.$Enums.VehicleType = {
  BICYCLE: 'BICYCLE',
  MOTORBIKE: 'MOTORBIKE',
  CAR: 'CAR',
  MINIVAN: 'MINIVAN',
  TRUCK: 'TRUCK'
};

exports.ShipmentStatus = exports.$Enums.ShipmentStatus = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  PICKED_UP: 'PICKED_UP',
  IN_TRANSIT: 'IN_TRANSIT',
  ARRIVED_AT_HUB: 'ARRIVED_AT_HUB',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  RETURNED: 'RETURNED',
  DISPUTED: 'DISPUTED'
};

exports.DeliveryTier = exports.$Enums.DeliveryTier = {
  STANDARD: 'STANDARD',
  EXPRESS: 'EXPRESS',
  SAME_DAY: 'SAME_DAY',
  INTERSTATE: 'INTERSTATE'
};

exports.AssignmentStatus = exports.$Enums.AssignmentStatus = {
  OFFERED: 'OFFERED',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  TIMED_OUT: 'TIMED_OUT'
};

exports.TransactionType = exports.$Enums.TransactionType = {
  CREDIT: 'CREDIT',
  DEBIT: 'DEBIT'
};

exports.LedgerCategory = exports.$Enums.LedgerCategory = {
  DELIVERY_PAYMENT: 'DELIVERY_PAYMENT',
  RIDER_EARNINGS: 'RIDER_EARNINGS',
  PLATFORM_COMMISSION: 'PLATFORM_COMMISSION',
  WALLET_TOPUP: 'WALLET_TOPUP',
  WITHDRAWAL: 'WITHDRAWAL',
  INSURANCE_PREMIUM: 'INSURANCE_PREMIUM',
  PROMO_DISCOUNT: 'PROMO_DISCOUNT',
  CASH_COLLECTION_REMITTANCE: 'CASH_COLLECTION_REMITTANCE'
};

exports.ChannelType = exports.$Enums.ChannelType = {
  IN_APP: 'IN_APP',
  PUSH: 'PUSH',
  SMS: 'SMS',
  EMAIL: 'EMAIL'
};

exports.Prisma.ModelName = {
  IncidentLog: 'IncidentLog',
  User: 'User',
  SavedAddress: 'SavedAddress',
  RiderProfile: 'RiderProfile',
  Vehicle: 'Vehicle',
  BusinessProfile: 'BusinessProfile',
  TransitHub: 'TransitHub',
  Shipment: 'Shipment',
  RiderAssignment: 'RiderAssignment',
  TrackingLog: 'TrackingLog',
  StatusTimeline: 'StatusTimeline',
  Wallet: 'Wallet',
  Transaction: 'Transaction',
  PromoCode: 'PromoCode',
  Review: 'Review',
  Notification: 'Notification',
  SupportTicket: 'SupportTicket'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
